name: Deploy CRA to Windows Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the CRA project
      run: npm run build

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Replace this with your actual deployment commands
        # For example, copying the build files to the server directory
        xcopy /s /e /y build\* C:\host\
